FROM ankur310794/tensorflow-pytorch:latest

RUN apt-get install git-lfs

RUN pip install --no-cache-dir git+https://github.com/deepset-ai/haystack.git
RUN pip install --no-cache-dir urllib3==1.25.4
RUN pip install --no-cache-dir torch==1.6.0+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html
